# Generated by Django 5.2.8 on 2025-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
    ]
