# Generated by Django 5.2.8 on 2025-11-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactinfo_facebook_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedures_image", models.ImageField(blank=True, upload_to="home/")),
                ("cosmetics_image", models.ImageField(blank=True, upload_to="home/")),
            ],
        ),
    ]
