# Generated by Django 5.2.8 on 2025-11-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_homepagesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinfo",
            name="map_embed_url",
        ),
    ]
