# Generated by Django 5.2.8 on 2025-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Акционная цена (меньше обычной)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
