# Generated by Django 5.2.8 on 2025-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmetics", "0002_alter_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Акційна ціна (менша за звичайну)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Залиште порожнім, якщо ціна не фіксована",
                max_digits=10,
                null=True,
            ),
        ),
    ]
